parameters:
  aws_region: ap-southeast-2
  ciinabox_role: ciinabox
  ops_account: 599070804856 # Defined here because unique across projects
  ops_account_dns_iam_role: arn:aws:iam::599070804856:role/Base2-Automatic-NS-Resolver
  source_bucket: source.tools.eonx.com.au

  # Enable/Disable components
  cli_enabled: false
  elasticsearch_enabled: false
  redis_enabled: false

  cloudformation:
    region: ap-southeast-2

    # IP blocks for gcs.config.yaml
    ip_blocks:
      public:
        - 0.0.0.0/0
      ops:
        - 52.64.2.223/32
        - 52.64.52.183/32
        - 52.64.86.162/32
        - 52.64.84.195/32
        - 52.64.59.124/32
        - 54.191.24.202/32
        - 54.200.105.138/32
      dev:
        - 115.70.204.250/32

  code:
    ecr_repo: 599070804856.dkr.ecr.ap-southeast-2.amazonaws.com
