services:
    _defaults:
        autowire: true
        public: true

    LoyaltyCorp\EasyCfhighlander\:
        resource: '../src'
        exclude: '../src/{HttpKernel,File/FileToGenerate.php}'

    Symplify\PackageBuilder\Parameter\ParameterProvider: ~
